name: Keep Render Alive
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -s "https://my-portfolio-nf5t.onrender.com/keep-alive" > /dev/null
